# Generated by Django 5.1.2 on 2024-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Tên đăng nhập')),
                ('password', models.CharField(max_length=200, verbose_name='Mật khẩu')),
                ('role', models.CharField(choices=[('sales_staff', 'Nhân viên bán hàng'), ('kitchen_staff', 'Nhân viên bếp'), ('owner', 'Chủ cửa hàng')], max_length=20, verbose_name='Vai trò')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Danh sách tài khoản',
            },
        ),
    ]
