# Generated by Django 5.1.2 on 2024-10-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='points_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points_used',
            field=models.IntegerField(default=0),
        ),
    ]
