# Generated by Django 5.1.2 on 2024-10-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_discount_order_points_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('paypal', 'PayPal')], default='cash', max_length=20),
        ),
    ]
