# Generated by Django 5.0.1 on 2024-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao')], default='Chờ duyệt', max_length=20),
        ),
    ]
