# Generated by Django 5.0.1 on 2024-11-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderstatus_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('default', 'Mặc định'), ('large', 'Lớn')], default='default', max_length=10),
        ),
    ]
