# Generated by Django 5.0.1 on 2024-11-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('default', 'Vừa'), ('large', 'Lớn')], default='default', max_length=10),
        ),
    ]
