# Generated by Django 5.0.1 on 2024-11-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_product_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Chờ duyệt', 'Chờ duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao'), ('Đã hủy', 'Đã hủy')], default='Chờ duyệt', max_length=20),
        ),
    ]
