# Generated by Django 5.0.1 on 2024-11-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_cancelled_reason_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled_reason',
        ),
    ]
