# Generated by Django 5.1.2 on 2024-10-27 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default='default_permission_code', max_length=100, unique=True, verbose_name='Mã quyền'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.permission', verbose_name='Quyền'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('owner', 'Chủ cửa hàng'), ('sales_staff', 'Nhân viên bán hàng'), ('kitchen_staff', 'Nhân viên bếp')], max_length=20, verbose_name='Vai trò'),
        ),
    ]
