# Generated by Django 5.1.2 on 2024-10-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_permission_code_alter_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Mã quyền'),
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permissions_permission',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='permissions_rolepermission',
        ),
    ]
