# Generated by Django 5.0.1 on 2024-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_large_size',
            field=models.BooleanField(default=True),
        ),
    ]
