# Generated by Django 5.0.1 on 2024-11-09 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstatistic',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerstatistic',
            name='order_count',
        ),
        migrations.RemoveField(
            model_name='customerstatistic',
            name='total_spent',
        ),
        migrations.RemoveField(
            model_name='productstatistic',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productstatistic',
            name='total_revenue',
        ),
        migrations.RemoveField(
            model_name='productstatistic',
            name='total_sold',
        ),
        migrations.RemoveField(
            model_name='revenuestatistic',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='revenuestatistic',
            name='daily_revenue',
        ),
        migrations.RemoveField(
            model_name='revenuestatistic',
            name='date',
        ),
        migrations.RemoveField(
            model_name='revenuestatistic',
            name='monthly_revenue',
        ),
        migrations.RemoveField(
            model_name='revenuestatistic',
            name='total_revenue',
        ),
    ]
