# Generated by Django 5.0.1 on 2024-11-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_remove_customerstatistic_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
