# Generated by Django 5.0.1 on 2024-12-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_delete_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativeReportStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
