# Generated by Django 5.0.1 on 2024-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_points'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='customer',
        ),
        migrations.AddField(
            model_name='table',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, related_name='tables', to='customers.customer'),
        ),
    ]
