# Generated by Django 5.0.1 on 2024-11-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_address_customer_email_customer_is_member'),
        ('tables', '0002_remove_table_customer_table_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='tables', to='customers.customer'),
        ),
    ]
