# Generated by Django 5.0.1 on 2024-11-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Sẵn sàng', 'Sẵn sàng'), ('Đang có khách', 'Đang có khách')], default='Sẵn sàng', max_length=20),
        ),
    ]
