# Generated by Django 5.0.1 on 2024-11-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
    ]
